### ISSUE TITLE
Aggregate results for ethics

### ISSUE THREAD

**Issue by jyhong836** [AI-secure/DecodingTrust#21]
**Describe the bug**
There is always a null in aggregated ACC of ethics, resulting in null final score.

**To Reproduce**
```shell
python src/dt/perspectives/machine_ethics/calculate_score.py
```

**Expected behavior**

**Screenshots**

The agg_zero is always null.
![image](https://github.com/AI-secure/DecodingTrust/assets/6964516/015c44ff-2b63-45ac-94ea-83bd0215f43d)

**Environment:**
 - Container
 - Conda Environment

**Additional context**

**Comment by chenweixin107** [comment]
You can check your model responses. If none of the responses is in OPTION_DIC["data_name"], then the corresponding accuracy will be null. You can also modify the OPTION_DIC to make it more align with your model outputs' format.

**Comment by jyhong836** [comment]
Thanks for your reply. Which file should I check? Or where can I find OPTION_DIC?

**Comment by chenweixin107** [comment]
Here is OPTION_DIC :
https://github.com/AI-secure/DecodingTrust/blob/9623dd2cd0a93d0bf79930fc195f85151cfb9dfe/src/dt/perspectives/machine_ethics/test_machine_ethics.py#L16
You can modify it to better adapt to the responses of your models :)
