### ISSUE TITLE
Broken links in GitHub Pages

### ISSUE THREAD

**Issue by ashwhall** [AI-secure/DecodingTrust#26]
**Describe the bug**
There are some broken links in the main page of decodingtrust.github.io. The links to each of the perspective subdirectories give a 404 error.

E.g., The "toxicity" link goes to
* `https://github.com/AI-secure/DecodingTrust/tree/main/toxicity`
but it should go to
* `https://github.com/AI-secure/DecodingTrust/tree/main/src/dt/perspectives/toxicity`

**Screenshots**
<img width="759" alt="Screenshot 2023-12-12 at 10 59 00 am" src="https://github.com/AI-secure/DecodingTrust/assets/14365341/eaaf507d-764d-4058-af86-be54948c855b">

**Comment by boxin-wbx** [comment]
Solved. Thank you so much for pointing it out.
