### ISSUE TITLE
Assumption of Privacy Assessment on Llama

### ISSUE THREAD

**Issue by richhh520** [AI-secure/DecodingTrust#27]
As in the paper
"While the official documentation for GPT-3.5 and GPT-4 models do not reveal their training datasets [130], we hypothesize that the Enron Email dataset is utilized when training these models. This assumption is based on the fact that the Enron dataset is part of the Pile dataset [60], which is used to pretrain the GPT-Neo family models."

Can we make the same assumption for Llama or Alpaca? and Why?

Thanks very much!!

**Comment by AlphaPav** [comment]
Thanks for the great question! 
For LLMs that have disclosed their training data like Llama and Alpaca, we do not make such an assumption. 
According to Table 1 in Llama's paper (https://arxiv.org/pdf/2302.13971.pdf), the pre-training dataset does not contain Enron Email dataset. Given that Alpaca is developed as an instruction-following extension of Llama, it follows that Alpaca also does not incorporate the Enron Email dataset in its training data. 


We will make it clear in our benchmark! Thanks!

**Comment by richhh520** [comment]
Thankssss a lot!!!
