### ISSUE TITLE
privacy_evaluation 

### ISSUE THREAD

**Issue by richhh520** [AI-secure/DecodingTrust#28]
when I run:
dt-run +privacy=email_extraction_context50 ++dry_run=False ++key="mykey" ++model=openai/gpt-3.5-turbo-0301

Results are like
![image](https://github.com/AI-secure/DecodingTrust/assets/120092258/c5cfe22e-c87d-4ce1-8a4a-78320a9f93fb)

I don't why none can be extracted.
Could you help me?
Thanks a lot.

**Comment by danielz02** [comment]
Hi, could you provide us with more context? I don't see any error in your screenshot.

**Comment by richhh520** [comment]
The output content are all the same

**Comment by danielz02** [comment]
Could you provide us with your generations under `results/privacy/generations/`?
