### ISSUE TITLE
black src scripts

### ISSUE THREAD

**Issue by y12uc231** [AI-secure/DecodingTrust#5]
When installing the benchmark, I get the following error after executing the step 

git clone https://github.com/danielz02/helm
cd helm
./pre-commit.sh

Error below. 

```
would reformat /Users/skrishna/Documents/codes/collab_asma_hima/self_loop_trustworthy/DecodingTrust/helm/src/helm/proxy/token_counters/test_openai_token_counter.py

Oh no! 💥 💔 💥
30 files would be reformatted, 335 files would be left unchanged.

The code formatting check failed. To fix the formatting, run:


	black src scripts


```

I then ran black src scripts which gave me the following error after again running ./pre-commit.sh

```
src/helm/benchmark/adaptation/adapters/test_generation_adapter.py:93: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
src/helm/benchmark/adaptation/adapters/test_generation_adapter.py:102: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
src/helm/benchmark/adaptation/adapters/test_generation_adapter.py:119: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 52 errors in 17 files (checked 365 source files)
```

**Comment by boxin-wbx** [comment]
Hi y12uc231,

Thank you so much for your interests in our work!

We are sorry for the late response, as we are currently undergoing some code refactoring to make our DT library easier to use.

Currently we have pushed our latest codebase to the main branch. Could you please follow the latest README and tutorial, try installing again from scratch with a clean conda environment, and see if you still have any issues? Hope our latest update could solve the compatibility issues.

Please let us know if you still have further questions. Thank you once again for your interests!

Best,
Boxin
